use_frameworks!

target 'DKLogin_Example' do
  pod 'DKLogin', :path => '../'

  target 'DKLogin_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
